name: Vertigo
version: 1.6
main: me.hawkfalcon.Vertigo.Vertigo
permissions: 
     vertigo.use:
        description: Allows use of plugin
        default: true
     vertigo.others:
        description: Allows use of commands that affect others
        default: OP
     vertigo.all:
        description: Allows use of /vertigo all
        default: OP
     vertigo.stop:
        description: Allows use of /vertigo stop
        default: true
        
commands:
    vertigo:
        description: main command
        usage: /vertigo

